### ISSUE TITLE
Cowduck gif is not visible if we go to a route that doesnt exist

### ISSUE THREAD

**Issue by Neelterminusdb** [terminusdb/terminusdb-website#29]
When we go to a different link that doesn't exist like https://terminusdb.com/404/bfekfge the cowduck gif which is supposed to display is not visible.

Screenshot:
<img width="1280" alt="Screenshot 2021-10-22 at 5 50 47 PM" src="https://user-images.githubusercontent.com/87318395/138452686-6325d409-378c-492c-9d76-c97323abe6dd.png">

**Comment by spl** [comment]
Interestingly, if you go deeper – https://terminusdb.com/404/bfekfge/aihwei – it gets even worse! All of the relative paths (`img`, `css`, and `js`) should be absolute.
<img width="887" alt="bad-404" src="https://user-images.githubusercontent.com/54900/139690307-6947472b-427a-487a-9de9-daf442d579ed.png">
